name: Pipeline Desafio 2026

on:
  push:
    branches:
      - prod
      - development    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment & Tags
        id: env-setup
        run: |
          if [[ "${{ github.ref }}" == refs/heads/prod ]]; then
            echo "ENV_NAME=production" >> $GITHUB_ENV
            echo "DOCKER_TAG=production,latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/development ]]; then
            echo "ENV_NAME=development" >> $GITHUB_ENV
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./asset/flask/Dockerfile
          push: true
          tags: |
            your-dockerhub-username/my-app:${{ env.DOCKER_TAG }}
          build-args: |
            CODE_ENV=${{ env.ENV_NAME }}
            FLASK_LOCAL_CACHE_DEFAULT_TIMEOUT=${{ env.FLASK_LOCAL_CACHE_DEFAULT_TIMEOUT }}
